### ISSUE TITLE
N番目の音楽を聞きたい時の動作について

### ISSUE THREAD

**Issue by moyomot** [walktan/hitsstream#53]
N番目の音楽を聞きたい時、移動ボタンを何度も押したくないです

**Comment by walktan** [comment]
以下機能を追加しました。https://github.com/walktan/hitsstream/pull/73
　・N番目のサムネイル画像をクリックした際に、N番目の曲を再生させる
　　(開発環境で動作検証済み)

恐れ入りますが、ご確認のほどお願いいたします

**Comment by walktan** [comment]
他の修正と競合するので、セルフレビューにより、Merge Pull Requestしちゃいます。
