### ISSUE TITLE
コントローラーのロジックをモデルに

### ISSUE THREAD

**Issue by moyomot** [walktan/hitsstream#54]
https://github.com/walktan/hitsstream/blob/master/app/controllers/ranks_controller.rb#L23-L24
全体的にロジックはモデルに書くと良いです
コントローラーとモデルの役割を考えましょう

**Comment by walktan** [comment]
修正しました。https://github.com/walktan/hitsstream/pull/58
恐れ入りますが、ご確認をお願いします。

（そもそもMVCをよく理解できていませんでした。。）

**Comment by walktan** [comment]
最修整しました。(誤って古いcommitを消してしましました。。)
#60
・モデル名の変更(ViewRanking→Ranking）
・三項演算子の利用

**Comment by walktan** [comment]
修正しました。
#60 
・view_rankingsを使用するのをやめて、controllerにActiveRecordを記述しました
