### ISSUE TITLE
テーブル定義について

### ISSUE THREAD

**Issue by moyomot** [walktan/hitsstream#55]
- `mst_` はわかりづらい
- `genre`, `music` というよりは、`itune`, `youtube`なのでは
- `mst_dates` 必要？ `ranks` の属性として存在すればOKだと思う
- `ranks`の命名も行けてない, itunesテーブルとyoutubesテーブルの関連テーブルがいいのかな

**Comment by walktan** [comment]
> mst_ はわかりづらい

マスタは`mst_`で始まるようにしていたのですが、Railsらしくないですね。

> mst_dates 必要？ ranks の属性として存在すればOKだと思う

`mst_dates`は、TOPページのプルダウン`Aggregate Date`の値リストとして
使用しているので、テーブルを切り分ける方が自然かな、と思いました。

以下のような変更を考えていますが、いかがでしょうか。

＜現状＞
mst_genres (name, itunes_url)
mst_musics (title, artist, youtube_url)
mst_dates (this_date)
ranks (rank, mst_date_id, mst_genre_id, mst_music_id)

＜変更案＞
itunes (genre, url)
youtubes (title, artist, url)
dates (this_date)
itunes_youtubes (rank, date_id, itune_id, youtube_id)

**Comment by moyomot** [comment]
>mst_datesは、TOPページのプルダウンAggregate Dateの値リストとして
使用しているので、テーブルを切り分ける方が自然かな、と思いました。

画面ありきでテーブル定義が決まるのは、ちょっと違うような気もしますが。
まあ、お任せします。

> itunes_youtubes

命名がいけてませんな

**Comment by walktan** [comment]
> >itunes_youtubes

>命名がいけてませんな

多対多になるので、上記の名称にしたのですが、そもそも、
(テーブル名)_(テーブル名)というのがナンセンスでしょうか？

**Comment by moyomot** [comment]
> (テーブル名)_(テーブル名)というのがナンセンスでしょうか？

そうですね、安直にそうするのは良くないと思います。
もっとわかりやすい命名があれば、そうするべきです。

**Comment by walktan** [comment]
>> (テーブル名)_(テーブル名)というのがナンセンスでしょうか？

>そうですね、安直にそうするのは良くないと思います。
>もっとわかりやすい命名があれば、そうするべきです。

`daily_rankings`はどうでしょうか？

**Comment by moyomot** [comment]
コメントしたら教えて下さい（毎日見てないので）
@moyomotつければOK

**Comment by walktan** [comment]
以下のように変更しました。https://github.com/walktan/hitsstream/pull/70
(開発環境にて、動作検証済)

＜変更前＞
mst_genres (id, name, itunes_url)
mst_musics (id, title, artist, youtube_url)
mst_dates (id, this_date)
ranks (id, rank, mst_date_id, mst_genre_id, mst_music_id)

＜変更後＞
itunes (itune_id, genre, itune_url)
youtubes (youtube_id, title, artist, youtube_url)
aggregate_dates (aggregate_date_id, this_date)
daily_rankings (daily_rankings_id, rank, aggregate_date_id, itune_id, youtube_id)

ご確認の程、お願いいたします。

**Comment by moyomot** [comment]
LGTM
